#!/bin/bash
mongo localhost:27017/supplier --eval 'db.supplier.aggregate([{$match:{$and:[ {"lineorder.part.p_category": "MFGR#12"},{s_region: "AMERICA"}]}},{$unwind: "$lineorder"}, {$match:{$and:[ {"lineorder.part.p_category": "MFGR#12"},{s_region: "AMERICA"}]}},{$project:{"lineorder.orderdate.d_year":1,"lineorder.part.p_brand1":1,"lineorder.lo_revenue":1}}, {$group:{_id:{d_year: "$lineorder.orderdate.d_year",p_brand1: "$lineorder.part.p_brand1"}, revenue:{$sum: "$lineorder.lo_revenue"}}}]).toArray()' >>~/Documentos/benchmark/mongoDB/suppliermo/query/shell/resultados/query21.txt

