#!/bin/bash
curl -XPOST 'localhost:9200/i_part/part2/_search?pretty' -d '
{
  "query": {
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "lineorder",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [ 
                  {"match": {"lineorder.supplier.s_nation":"UNITED STATES"}},
		  {"match": {"lineorder.customer.c_nation":"UNITED STATES"}},
		  {"range": {"lineorder.orderdate.d_year":{"gte":1992,"lte":1997}}}  
                ]
         }}}}}}}
},
  "aggs": {
    "lineorder": {
      "nested": {
        "path": "lineorder"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                  {"match": {"lineorder.supplier.s_nation":"UNITED STATES"}},
		  {"match": {"lineorder.customer.c_nation":"UNITED STATES"}},
		  {"range": {"lineorder.orderdate.d_year":{"gte":1992,"lte":1997}}} 
                 ]
                }
			   },
          "aggs": {
   		 "year": {
     		 "terms": {
      		  "field": "lineorder.orderdate.d_year",
            "order" : { "_term" : "asc" }
     		  },
		    "aggs": {
   		 "c_nation": {
     		 "terms": {
      		  "field": "lineorder.customer.c_city",
            "order" : { "_term" : "asc" }
     		  }, 
		  "aggs": {
   		 "s_nation": {
     		 "terms": {
      		  "field": "lineorder.supplier.s_city",
            "order" : { "_term" : "asc" }			  
     		  },
			"aggs": {
    			"sum_revenue": {
    			  "sum": {
     		        "field": "lineorder.lo_revenue"
		     }
			}}}}}}}}}}}

},"sort" : [
      {"lineorder.orderdate.d_year" : {"order" : "asc"}},{"lineorder.lo_revenue" : {"order" : "desc"}}
   ],"size":0
}' -o /home/raphael/Documentos/benchmark/elasticsearch/part/resultados/query32.txt
