#!/bin/bash
curl -XPOST 'localhost:9200/i_part/part2/_search?pretty' -d '
{
  "query": {
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "lineorder",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [ 
                 {"bool":{"should":[{"match": {"lineorder.supplier.s_city":"UNITED KI1"}},{"match": {"lineorder.supplier.s_city":"UNITED KI5"}}]}},
		  {"bool":{"should":[{"match": {"lineorder.customer.c_city":"UNITED KI1"}},{"match": {"lineorder.customer.c_city":"UNITED KI5"}}]}},	  
		  {"match": {"lineorder.orderdate.d_yearmonthnum":199712}}  
                ]
         }}}}}}}
},
  "aggs": {
    "lineorder": {
      "nested": {
        "path": "lineorder"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                   {"bool":{"should":[{"match": {"lineorder.supplier.s_city":"UNITED KI1"}},{"match": {"lineorder.supplier.s_city":"UNITED KI5"}}]}},
		  {"bool":{"should":[{"match": {"lineorder.customer.c_city":"UNITED KI1"}},{"match": {"lineorder.customer.c_city":"UNITED KI5"}}]}},	  
		  {"match": {"lineorder.orderdate.d_yearmonthnum":199712}}  
                 ]
                }
			   },
          "aggs": {
   		 "year": {
     		 "terms": {
      		  "field": "lineorder.orderdate.d_year",
            "order" : { "_term" : "asc" }, "size": 10000
     		  },
		    "aggs": {
   		 "c_nation": {
     		 "terms": {
      		  "field": "lineorder.customer.c_city",
            "order" : { "_term" : "asc" }, "size": 10000
     		  }, 
		  "aggs": {
   		 "s_nation": {
     		 "terms": {
      		  "field": "lineorder.supplier.s_city",
            "order" : { "_term" : "asc" }, "size": 10000			  
     		  },
			"aggs": {
    			"sum_revenue": {
    			  "sum": {
     		        "field": "lineorder.lo_revenue"
		     }
			}}}}}}}}}}}

},"size":0
}' -o /home/raphael/Documentos/benchmark/elasticsearch/part/resultados/query34.txt
