#!/bin/bash
curl -XPOST 'localhost:9200/i_part/part2/_search?pretty' -d '
{
  "query": {"filtered": {"filter": {
	"bool": {
	      "must": [
		{"match": {"p_category":"MFGR#14"}}, 
		{
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "lineorder",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [ 
                  {"match": {"lineorder.customer.c_region":"AMERICA"}},
		              {"match": {"lineorder.supplier.s_nation":"UNITED STATES"}},
		              {"range": {"lineorder.orderdate.d_year":{"gte":1997,"lte":1998}}} 
                ]
         }}}}}}}}]}}}
},
"aggs": {
   		 	"p_brand1": {
     		 	"terms": {
      		 	 "field": "p_brand1",
            "order" : { "_term" : "asc" }, "size": 10000
      		         },
  "aggs": {
    "lineorder": {
      "nested": {
        "path": "lineorder"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                  {"match": {"lineorder.customer.c_region":"AMERICA"}},
		              {"match": {"lineorder.supplier.s_nation":"UNITED STATES"}},
		              {"range": {"lineorder.orderdate.d_year":{"gte":1997,"lte":1998}}}  
                 ]
                }
			   },
          "aggs": {
   		 "year": {
     		 "terms": {
      		  "field": "lineorder.orderdate.d_year",
            "order" : { "_term" : "asc" }, "size": 10000
     		  },
		    "aggs": {
   		 "s_city": {
     		 "terms": {
      		  "field": "lineorder.supplier.s_city",
            "order" : { "_term" : "asc" }, "size": 10000
     		  }, 
			"aggs": {
    			"profit": {
    			  "sum": {
     		        "script" : "doc[\"lineorder.lo_revenue\"].value - doc[\"lineorder.lo_supplycost\"].value"
		     }
			}}}}}}}}}}}
},"size":0
}' -o /home/raphael/Documentos/benchmark/elasticsearch/part/resultados/query43.txt
