#!/bin/bash
curl -XPOST 'localhost:9200/i_part/part2/_search?pretty' -d '
{
  "query": {"filtered": {"filter": {
    "bool": {
      "must": [
        { "term": { "p_brand1":"MFGR#2221"}}, 
        {
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "lineorder",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [ 
                  {"term": {"lineorder.supplier.s_region":"EUROPE"}}  
                ]
               }
              }
            }
          }
        }
      }
    }
  }
]
}}}
},"aggs": {
   		 	"group_by_brand": {
     		 	"terms": {
      		 	 "field": "p_brand1",
            "order" : { "_term" : "asc" }
      		         },
  "aggs": {
    "lineorder": {
      "nested": {
        "path": "lineorder"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                  {"term": {"lineorder.supplier.s_region":"EUROPE"}} 
                ]
               }
			   },
          "aggs": {
   		 "group_by_year": {
     		 "terms": {
      		  "field": "lineorder.orderdate.d_year",
            "order" : { "_term" : "asc" }
     		  },
			"aggs": {
    			"sum_revenue": {
    			  "sum": {
     		        "field": "lineorder.lo_revenue"
      }}}
      }
    }
  }
  }
        }
		}
  }
},"sort" : [
      {"lineorder.orderdate.d_year" : {"order" : "asc"}},{"p_brand1" : {"order" : "asc"}}
   ], "size":0
}' -o /home/raphael/Documentos/benchmark/elasticsearch/part/resultados/query23.txt
