#!/bin/bash
curl -XPOST 'localhost:9200/i_supplier/supplier/_search?pretty' -d '
{
  "query": {
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "lineorder",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [ 
                  {"term": {"lineorder.orderdate.d_yearmonthnum":199401}},
                  {"range" : {"lineorder.lo_discount":{"gte":4, "lte":6}}},
			{"range" : {"lineorder.lo_quantity":{"gte":26, "lte":35}}}  
                ]
               }
              }
            }
          }
        }
      }
    }
  },
  "aggs": {
    "lineorder": {
      "nested": {
        "path": "lineorder"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                  {"term": {"lineorder.orderdate.d_yearmonthnum":199401}},
                  {"range" : {"lineorder.lo_discount":{"gte":4, "lte":6}}},
			{"range" : {"lineorder.lo_quantity":{"gte":26, "lte":35}}}  
                ]
               }
			   },
          "aggs": {
            "extended_price": {
              "sum": {"script" : "doc[\"lineorder.lo_extendedprice\"].value * doc[\"lineorder.lo_discount\"].value"
            }
            }
          }
        }
		}
  }
}, "size":0
}' -o /home/raphael/Documentos/benchmark/elasticsearch/supplier/resultados/query12.txt
