#!/bin/bash
curl -XPOST 'localhost:9200/i_supplier/supplier/_search?pretty' -d '
{
  "query": {"filtered": {"filter": {
  "bool": {
	      "must": [
		  {"term": {"s_region":"ASIA"}},
		{
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "lineorder",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [ 
                  {"term": {"lineorder.customer.c_region":"ASIA"}}, 
		  {"range": {"lineorder.orderdate.d_year":{"gte":1992,"lte":1997}}}  
                ]
         }}}}}}}
}]}}}},
  "aggs": {
   		 "s_nation": {
     		 "terms": {
      		  "field": "s_nation",
            "order" : { "_term" : "asc" }
     		  },
  "aggs": {
    "lineorder": {
      "nested": {
        "path": "lineorder"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                 {"term": {"lineorder.customer.c_region":"ASIA"}}, 
		  {"range": {"lineorder.orderdate.d_year":{"gte":1992,"lte":1997}}}  
                 ]
                }
			   },
          "aggs": {
   		 "year": {
     		 "terms": {
      		  "field": "lineorder.orderdate.d_year",
            "order" : { "_term" : "asc" }
     		  }, 
		  "aggs": {
   		 "c_nation": {
     		 "terms": {
      		  "field": "lineorder.customer.c_nation",
            "order" : { "_term" : "asc" }			  
     		  },
			"aggs": {
    			"sum_revenue": {
    			  "sum": {
     		        "field": "lineorder.lo_revenue"
                }
			}}}}}}}}}}}

},"sort" : [{"lineorder.lo_revenue" : {"order" : "desc"}}],"size":0
}' -o /home/raphael/Documentos/benchmark/elasticsearch/supplier/resultados/query31.txt
