#!/bin/bash
curl -XPOST 'localhost:9200/i_supplier/supplier/_search?pretty' -d '
{
  "query": {"filtered": {"filter": {
	"bool": {
	      "must": [
        {"term": {"s_region":"AMERICA"}}, 
		{
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "lineorder",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [ 
       {"bool":{"should":[{"term": {"lineorder.part.p_mfgr":"MFGR#1"}},{"term": {"lineorder.part.p_mfgr":"MFGR#2"}}]}},            
		  {"term": {"lineorder.customer.c_region":"AMERICA"}}
                ]
         }}}}}}}}]}}}
},
  "aggs": {
    "lineorder": {
      "nested": {
        "path": "lineorder"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                   {"bool":{"should":[{"term": {"lineorder.part.p_mfgr":"MFGR#1"}},{"term": {"lineorder.part.p_mfgr":"MFGR#2"}}]}},            
		  {"term": {"lineorder.customer.c_region":"AMERICA"}}
                 ]
                }
			   },
          "aggs": {
   		 "year": {
     		 "terms": {
      		  "field": "lineorder.orderdate.d_year",
            "order" : { "_term" : "asc" }
     		  },
          "aggs": {
   		 "c_nation": {
     		 "terms": {
      		  "field": "lineorder.customer.c_nation",
            "order" : { "_term" : "asc" }
     		  },
			"aggs": {
    			"profit": {
    			  "sum": {"script" : "doc[\"lineorder.lo_revenue\"].value - doc[\"lineorder.lo_supplycost\"].value"}
			}}}}}}}}}

},"size":0
}' -o /home/raphael/Documentos/benchmark/elasticsearch/supplier/resultados/query41.txt
