#!/bin/bash
curl -XPOST 'localhost:9200/i_customer/customer/_search?pretty' -d '
{
  "query": {
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "lineorder",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [ 
                  {"term": {"lineorder.orderdate.d_weeknuminyear":6}},
		  {"term": {"lineorder.orderdate.d_year":1994}},
                  {"range" : {"lineorder.lo_discount":{"gte":5, "lte":7}}},
		  {"range" : {"lineorder.lo_quantity":{"gte":26, "lte":35}}}  
                ]
               }
              }
            }
          }
        }
      }
    }
  },
  "aggs": {
    "lineorder": {
      "nested": {
        "path": "lineorder"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                  {"term": {"lineorder.orderdate.d_weeknuminyear":6}},
		  {"term": {"lineorder.orderdate.d_year":1994}},
                  {"range" : {"lineorder.lo_discount":{"gte":5, "lte":7}}},
		  {"range" : {"lineorder.lo_quantity":{"gte":26, "lte":35}}} 
                ]
               }
			   },
          "aggs": {
            "extended_price": {
              "sum": {"script" : "doc[\"lineorder.lo_extendedprice\"] * doc[\"lineorder.lo_discount\"]"
            }
 }
            }
          }
        }
		}
}, "size":0
}' -o /home/raphael/Documentos/benchmark/elasticsearch/customer/resultados/query13.txt
