#!/bin/bash
mongo localhost:27017/lineorder --eval 'db.lineorder.aggregate([{$match:{$and:[{"orderdate.d_year":{$gte:1992}},{"orderdate.d_year":{$lte:1997}},{"supplier.s_nation":"UNITED STATES"},{"customer.c_nation":"UNITED STATES"}]}},{$project:{"customer.c_city":1,"supplier.s_city":1,"orderdate.d_year":1,lo_revenue:1}},{$group:{_id:{c_city:"$customer.c_city", s_city:"$supplier.s_city",d_year: "$orderdate.d_year"}, revenue:{$sum: "$lo_revenue"}}}]).toArray()' >>~/Documentos/benchmark/mongoDB/lineordermo/query/shell/resultados/query32.txt


