#!/bin/bash
mongo localhost:27017/lineorder --eval 'db.lineorder.aggregate([{$match:{$and:[{lo_discount:{$in:[1,2,3]}},{lo_quantity:{$lt:25}},{"orderdate.d_year": 1993}]}},{$project:{"orderdate.d_datekey":1, des:{$multiply:["$lo_extendedprice","$lo_discount",0.01]}}},{$group:{_id:null, revenue:{$sum:"$des"}}}]).toArray()' >>~/Documentos/benchmark/mongoDB/lineordermo/query/shell/resultados/query11.txt

