#!/bin/bash
mongo localhost:27017/lineorder --eval 'db.lineorder.aggregate([{$match:{$and:[ {lo_discount:{$in:[5,6,7]}},{lo_quantity:{$gte:26}},{lo_quantity:{$lte:35}}, {"orderdate.d_weeknuminyear": 6},{"orderdate.d_year": 1994}]}},{$project:{"orderdate.d_datekey":1, des:{$multiply:["$lo_extendedprice","$lo_discount",0.01]}}},{$group:{_id:null, revenue:{$sum:"$des"}}}]).toArray()' >>~/Documentos/benchmark/mongoDB/lineordermo/query/shell/resultados/query13.txt

