#!/bin/bash
mongo localhost:27017/lineorder --eval 'db.lineorder.aggregate([{$match:{$and:[ {"part.p_category": "MFGR#12"},{"supplier.s_region": "AMERICA"}]}},{$project:{"orderdate.d_year":1,"part.p_brand1":1,lo_revenue:1}}, {$group:{_id:{d_year: "$orderdate.d_year",p_brand1: "$part.p_brand1"}, revenue:{$sum: "$lo_revenue"}}}]).toArray()' >>~/Documentos/benchmark/mongoDB/lineordermo/query/shell/resultados/query21.txt

