#!/bin/bash
mongo localhost:27017/lineorder --eval 'db.lineorder.aggregate([{$match:{$and:[{"customer.c_region":"AMERICA"},{"supplier.s_region": "AMERICA"},{$or:[{"part.p_mfgr":"MFGR#1"},{"part.p_mfgr":"MFGR#2"}]}]}},{$project:{"orderdate.d_year":1,"customer.c_nation":1,dim:{$subtract:["$lo_revenue","$lo_supplycost"]}}},{$group:{_id:{d_year:"$orderdate.d_year",c_nation:"$customer.c_nation"}, profit:{$sum: "$dim"}}}]).toArray()' >>~/Documentos/benchmark/mongoDB/lineordermo/query/shell/resultados/query41.txt

