#!/bin/bash
mongo localhost:27017/lineorder --eval 'db.lineorder.aggregate([{$match:{$and:[{"customer.c_region":"AMERICA"},{"supplier.s_nation": "UNITED STATES"},{$or:[{"orderdate.d_year":1997},{"orderdate.d_year":1998}]},{"part.p_category":"MFGR#14"}]}},{$project:{"orderdate.d_year":1,"supplier.s_city":1,"part.p_brand1":1,dim:{$subtract:["$lo_revenue","$lo_supplycost"]}}},{$group:{_id:{d_year:"$orderdate.d_year",s_city:"$supplier.s_city",p_brand1:"$part.p_brand1"}, profit:{$sum: "$dim"}}}]).toArray()' >>~/Documentos/benchmark/mongoDB/lineordermo/query/shell/resultados/query43.txt

