#!/bin/bash
curl -XPOST 'localhost:9200/i_lineorder/lineorder/_search?pretty' -d '
{
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                {"term": {"supplier.s_region":"ASIA"}},
                 {"term": {"customer.c_region":"ASIA"}}, 
		  {"range": {"orderdate.d_year":{"gte":1992,"lte":1997}}}  
                 ]
                }
			   },
          "aggs": {
   		 "year": {
     		 "terms": {
      		  "field": "orderdate.d_year",
            "order" : { "_term" : "asc" }
     		  }, 
		  "aggs": {
   		 "c_nation": {
     		 "terms": {
      		  "field": "customer.c_nation",
            "order" : { "_term" : "desc" }			  
     		  },
          "aggs": {
   		 "s_nation": {
     		 "terms": {
      		  "field": "supplier.s_nation",
            "order" : { "sum_revenue" : "desc" }
     		  },
			"aggs": {
    			"sum_revenue": {
    			  "sum": {
     		        "field": "lo_revenue"
                }
			}}}}}}}}}
},"sort" : [{"lo_revenue" : {"order" : "desc"}}],"size":0
}' -o /home/raphael/Documentos/benchmark/elasticsearch/lineorder/resultados/query31.txt
