#!/bin/bash
curl -XPOST 'localhost:9200/i_lineorder/lineorder/_search?pretty' -d '
{
      "aggs": {
	  "lineorder": {
          "filter": {
                "bool": {
                "must": [ 
                {"term": {"supplier.s_region":"EUROPE"}}, 
                  { "term": { "part.p_brand1":"MFGR#2221"}} 
                ]
               }
			   },
          "aggs": {
   		 "group_by_year": {
     		 "terms": {
      		  "field": "orderdate.d_year",
            "order" : { "_term" : "asc" }
     		  },
          "aggs": {
   		 	"group_by_brand": {
     		 	"terms": {
      		 	 "field": "part.p_brand1",
            "order" : { "_term" : "asc" }
      		         },
			"aggs": {
    			"sum_revenue": {
    			  "sum": {
     		        "field": "lo_revenue"
      }
      }
    }
  }
  }
        }
		}
  }
}, "size":0
}' -o /home/raphael/Documentos/benchmark/elasticsearch/lineorder/resultados/query23.txt
