#!/bin/bash
mongo localhost:27017/part --eval 'db.part.aggregate([{"$match":{"$and":[ {"p_category": "MFGR#12"},{"lineorder.supplier.s_region": "AMERICA"}]}},{"$unwind": "$lineorder"}, {"$match":{"$and":[ {"p_category": "MFGR#12"},{"lineorder.supplier.s_region": "AMERICA"}]}},{"$project":{"lineorder.orderdate.d_year":1,"p_brand1":1,"lineorder.lo_revenue":1}}, {"$group":{"_id":{"d_year": "$lineorder.orderdate.d_year","p_brand1": "$p_brand1"}, "revenue":{"$sum": "$lineorder.lo_revenue"}}}]).toArray()' >>~/Documentos/benchmark/mongoDB/partmo/query/shell/resultados/query21.txt

