#!/bin/bash
curl -XPOST 'localhost:9200/i_orderdate/orderdate/_search?pretty' -d '
{
  "query": {"filtered": {"filter": {
	"bool": {
	      "must": [
        {"range": {"d_year":{"gte":1997,"lte":1998}}}, 
		{
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "lineorder",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [ 
                  {"bool":{"should":[{"term": {"lineorder.part.p_mfgr":"MFGR#1"}},{"term": {"lineorder.part.p_mfgr":"MFGR#2"}}]}},  
                  {"term": {"lineorder.customer.c_region":"AMERICA"}},
		              {"term": {"lineorder.supplier.s_region":"AMERICA"}}
                ]
         }}}}}}}}]}}}
},
"aggs": {
   		 "year": {
     		 "terms": {
      		  "field": "d_year",
            "order" : { "_term" : "asc" }
     		  },
  "aggs": {
    "lineorder": {
      "nested": {
        "path": "lineorder"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                  {"bool":{"should":[{"term": {"lineorder.part.p_mfgr":"MFGR#1"}},{"term": {"lineorder.part.p_mfgr":"MFGR#2"}}]}},    
         {"term": {"lineorder.customer.c_region":"AMERICA"}},
		   {"term": {"lineorder.supplier.s_region":"AMERICA"}} 
                 ]
                }
			   }, 
          "aggs": {
   		 "s_nation": {
     		 "terms": {
      		  "field": "lineorder.supplier.s_nation",
            "order" : { "_term" : "asc" }
     		  },
          "aggs": {
   		 "p_category": {
     		 "terms": {
      		  "field": "lineorder.part.p_category",
            "order" : { "_term" : "asc" }
     		  },
			"aggs": {
    			"profit": {
    			  "sum": {"script" : "doc[\"lineorder.lo_revenue\"].value - doc[\"lineorder.lo_supplycost\"].value"
		     }
			}}}}}}}}}}}
},"size":0
}' -o /home/raphael/Documentos/benchmark/elasticsearch/orderdate/resultados/query42.txt 
