#!/bin/bash
curl -XPOST 'localhost:9200/i_orderdate/orderdate/_search?pretty' -d '
{
  "query": {"filtered": {"filter": {
  "bool": {
	      "must": [
        {"range": {"d_year":{"gte":1992,"lte":1997}}},  

		{
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "lineorder",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [ 
                  {"term": {"lineorder.supplier.s_region":"ASIA"}},
                  		{"term": {"lineorder.customer.c_region":"ASIA"}} 
                ]
         }}}}}}}
}]}}}},
"aggs": {
   		 "year": {
     		 "terms": {
      		  "field": "d_year",
            "order" : { "_term" : "asc" }
     		  },
  "aggs": {
    "lineorder": {
      "nested": {
        "path": "lineorder"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                  {"term": {"lineorder.supplier.s_region":"ASIA"}},
                  		{"term": {"lineorder.customer.c_region":"ASIA"}} 
                 ]
                }
			   },
          "aggs": {
   		 "c_nation": {
     		 "terms": {
      		  "field": "lineorder.customer.c_nation",
            "order" : { "_term" : "asc" }
     		  },
		  "aggs": {
   		 "s_nation": {
     		 "terms": {
      		  "field": "lineorder.supplier.s_nation",
            "order" : { "_term" : "asc" }			  
     		  },
			"aggs": {
    			"sum_revenue": {
    			  "sum": {
     		        "field": "lineorder.lo_revenue"
                }
			}}}}}}}}}}}

},"size":0
}' -o /home/raphael/Documentos/benchmark/elasticsearch/orderdate/resultados/query31.txt 
