#!/bin/bash
curl -XPOST 'localhost:9200/i_orderdate/orderdate/_search?pretty' -d '
{
  "query": {"filtered": {"filter": {
	"bool": {
	      "must": [
        {"range": {"d_year":{"gte":1997,"lte":1998}}}, 
		{
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "lineorder",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [ 
                  {"term": {"lineorder.part.p_category":"MFGR#14"}},             
		  {"term": {"lineorder.supplier.s_nation":"UNITED STATES"}},
		  {"term": {"lineorder.customer.c_region":"AMERICA"}} 
                ]
         }}}}}}}}]}}}
},
"aggs": {
   		 "year": {
     		 "terms": {
      		  "field": "d_year",
            "order" : { "_term" : "asc" }, "size": 10000
     		  },
  "aggs": {
    "lineorder": {
      "nested": {
        "path": "lineorder"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                  {"term": {"lineorder.part.p_category":"MFGR#14"}},             
		  {"term": {"lineorder.supplier.s_nation":"UNITED STATES"}},
		  {"term": {"lineorder.customer.c_region":"AMERICA"}} 
                 ]
                }
			   }, 
          "aggs": {
   		 "s_city": {
     		 "terms": {
      		  "field": "lineorder.supplier.s_city",
            "order" : { "_term" : "asc" }, "size": 10000
     		  },
           "aggs": {
   		 "p_brand1": {
     		 "terms": {
      		  "field": "lineorder.part.p_brand1",
            "order" : { "_term" : "asc" }, "size": 10000
     		  },
			"aggs": {
    			"profit": {
    			  "sum": {"script" : "doc[\"lineorder.lo_revenue\"].value - doc[\"lineorder.lo_supplycost\"].value"
		     }
			}}}}}}}}}}}
},"size":0}' -o /home/raphael/Documentos/benchmark/elasticsearch/orderdate/resultados/query43.txt 
