#!/bin/bash
curl -XPOST 'localhost:9200/i_orderdate/orderdate/_search?pretty' -d '
{
  "query": {"filtered": {"filter": {
   "bool": {
	      "must": [
		{"term": {"d_weeknuminyear":6}},
		  {"term": {"d_year":1994}},
		{
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "lineorder",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [ 
                  {"range" : {"lineorder.lo_discount":{"gte":5, "lte":7}}},
		  {"range" : {"lineorder.lo_quantity":{"gte":26, "lte":35}}}  
                ]
               }
              }
            }
          }
        }
      }
    }
  }
  ]
  }
  }}},
  "aggs": {
    "lineorder": {
      "nested": {
        "path": "lineorder"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                 {"range" : {"lineorder.lo_discount":{"gte":5, "lte":7}}},
		  {"range" : {"lineorder.lo_quantity":{"gte":26, "lte":35}}}   
                ]
               }
			   },"aggs": {
          "extended_price": {
              "sum": {"script" : "doc[\"lineorder.lo_extendedprice\"] * doc[\"lineorder.lo_discount\"]"
            }
            }
          }
        }
	}
  }
}, "size":0
}' -o /home/raphael/Documentos/benchmark/elasticsearch/orderdate/resultados/query13.txt 



