#!/bin/bash
curl -XPOST 'localhost:9200/i_orderdate/orderdate/_search?pretty' -d '
{
  "query": {"filtered": {"filter": {
  "bool": {
	      "must": [
        {"term": {"d_yearmonthnum":199712}}, 
		{
    "filtered": {
      "filter": {
        "nested": {
          "inner_hits": {},
          "path": "lineorder",
          "query": {
            "filtered": {
              "filter": {
                "bool": {
                "must": [ 
                   {"bool":{"should":[{"term": {"lineorder.supplier.s_city":"UNITED KI1"}},{"term": {"lineorder.supplier.s_city":"UNITED KI5"}}]}},
		             {"bool":{"should":[{"term": {"lineorder.customer.c_city":"UNITED KI1"}},{"term": {"lineorder.customer.c_city":"UNITED KI5"}}]}}  
                ]
         }}}}}}}
}]}}}},
 "aggs": {
   		 "year": {
     		 "terms": {
      		  "field": "d_year",
            "order" : { "_term" : "asc" }
     		  },
  "aggs": {
    "lineorder": {
      "nested": {
        "path": "lineorder"
      },
      "aggs": {
	  "only_loc": {
          "filter": {
                "bool": {
                "must": [ 
                  {"bool":{"should":[{"term": {"lineorder.supplier.s_city":"UNITED KI1"}},{"term": {"lineorder.supplier.s_city":"UNITED KI5"}}]}},
		             {"bool":{"should":[{"term": {"lineorder.customer.c_city":"UNITED KI1"}},{"term": {"lineorder.customer.c_city":"UNITED KI5"}}]}}  
                 ]
                }
			   },
          "aggs": {
   		 "c_nation": {
     		 "terms": {
      		  "field": "lineorder.customer.c_city",
            "order" : { "_term" : "asc" }
     		  },
		  "aggs": {
   		 "s_nation": {
     		 "terms": {
      		  "field": "lineorder.supplier.s_city",
            "order" : { "_term" : "asc" }			  
     		  },
			"aggs": {
    			"sum_revenue": {
    			  "sum": {
     		        "field": "lineorder.lo_revenue"
                }
			}}}}}}}}}}}

},"sort" : [{"lineorder.lo_revenue" : {"order" : "desc"}}],"size":0
}' -o /home/raphael/Documentos/benchmark/elasticsearch/orderdate/resultados/query34.txt 
